Feature/tx store
hyperledger/iroha-ametsuchi pull request #50
Opened 2017-03-25 14:15 UTC by kamilsa

please review

2017-03-25 19:08 UTC, Warchant requested changes

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +  return iterator;
here you create *local* variable and return its *address*.
There will be undefined behavior.

Return copy, without `&`.

Read about "Return Value Optimization (RVO)"

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +  return iterator;
i guess it can be simplified to 
```
n_ += 1;
return this;
```

no?

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +Array::RandomAccessIterator& Array::RandomAccessIterator::operator--() {
again, reference to local variable returned

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +  return iterator;
can be simplified
```
n_ -= 1;
return this;
```
?

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +Array::RandomAccessIterator &Array::RandomAccessIterator::operator+=(const int& n) {
again, reference to local variable returned

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +Array::RandomAccessIterator &Array::RandomAccessIterator::operator+=(const int& n) {
Also, primitive types can be passed by value :)

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +Array::RandomAccessIterator &Array::RandomAccessIterator::operator-=(const int &n) {
again, reference to local variable returned

2017-03-25 19:08 UTC, Warchant commented on src/ametsuchi/tx_store/iterator.cc
> +  RandomAccessIterator iterator(*this);
same as before, can be simplified.

2017-03-26 14:07 UTC, l4l requested changes

2017-03-26 14:07 UTC, l4l commented on test/ametsuchi/tx_store/tx_store_iterator_test.cc
> +  for (auto it = begin; it < end; it++) {
you can use:
```
int i = 0;
std::for_each(array_.begin(), array.end(), [&i](const auto &e){
  ASSERT_EQ(test_set[i], e);
  i++;
});
```

2017-03-26 14:07 UTC, l4l commented on test/ametsuchi/tx_store/tx_store_recovery_test.cc
> +  ASSERT_EQ(array_.get(0), ByteArray{});
maybe `ASSERT_EQ(array_.get(0).size(), 0);`? so it don't need to call constructor

2017-03-26 14:07 UTC, l4l commented on test/ametsuchi/tx_store/tx_store_recovery_test.cc
> +}  // ametsuchi
\n

2017-03-26 14:07 UTC, l4l commented on test/ametsuchi/tx_store/tx_store_test.cc
> +/**
maybe unite w/ prev file?

2017-03-27 17:05 UTC, Warchant commented on include/ametsuchi/tx_store/array.h
> +#define AMETSUCHI_ARRAY_H
its ok to use include guards

2017-03-27 17:07 UTC, Warchant commented on test/ametsuchi/tx_store/tx_store_iterator_test.cc
> +  for (auto it = begin; it < end; it++) {
```
size_t i=0;
for(auto&& v: array_){
  ASSERT_EQ(test_set[i++], v);
}
```

2017-03-27 17:52 UTC, emilmelnikov requested changes
Do not leave commented code in repository or, if it serves some purpose, write a comment on why it has been commented out. You can always look at the repository for the old code if needed.

2017-03-27 17:52 UTC, emilmelnikov commented on include/ametsuchi/tx_store/array.h
>    std::size_t uncommitted_size_; // size (in bytes) of uncommited changes (don't confuse with uncommited_.size() )
Please rename either this variable or `uncommitted.size()`.

2017-03-27 17:52 UTC, emilmelnikov commented on include/ametsuchi/tx_store/array.h
> +  //std::vector<ByteArray> uncommitted_; // vector of uncommitted changes
Don't leave commented code or explain why it has been commented out.

2017-03-27 17:52 UTC, emilmelnikov commented on include/ametsuchi/tx_store/index.h
> +  std::size_t append_batch(std::vector<file::offset_t> &offsets);
Add `const` to the parameter (looks like this method doesn't modify the parameter).

2017-03-27 17:52 UTC, emilmelnikov commented on src/ametsuchi/tx_store/array.cc
> +  /*
Commented code should be removed or explained.

2017-03-27 17:52 UTC, emilmelnikov commented on src/ametsuchi/tx_store/array.cc
> +  std::for_each(batch_data.begin(), batch_data.end(), [](const auto & e){
When using lambdas, specify all parameters in the capture list explicitly.

2017-03-27 17:52 UTC, emilmelnikov commented on src/ametsuchi/tx_store/array.cc
> +{
Use formatting style from `.clang-format`.

2017-03-28 09:41 UTC, Warchant commented on test/ametsuchi/tx_store/tx_store_iterator_test.cc
> +  for (auto it = begin; it < end; it++) {
Also, always use prefix increment operator with iterators (get rid on 1 memory allocation = faster)

```
++it
```

2017-03-29 15:35 UTC, satellitex commented on src/ametsuchi/tx_store/index.cc
> +
What about using cache here?
And I think `txstore::Array.get(n)` should use cache too.

2017-03-30 14:43 UTC, Warchant commented
WIP

2017-04-05 10:09 UTC, Warchant commented
Deprecated

2017-04-05 10:09 UTC, closed without merging